services:
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:/root/.prefect
    environment:
      - PREFECT_UI_API_URL=http://localhost:4200/api

  prefect-worker:
    build: .
    restart: unless-stopped
    command: prefect worker start --pool wolf-tracks-pool --type process
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    env_file: .env
    depends_on:
      - prefect-server
    volumes:
      - ./extract:/app/extract
      - ./load:/app/load
      - ./scripts:/app/scripts
      - ./transform:/app/transform
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # Main pipeline services - runs extract + load + dbt
  pipeline:
    build: .
    env_file: .env
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      # Mounting code so it can be edited locally and run in the container
      - ./extract:/app/extract
      - ./load:/app/load
      - ./scripts:/app/scripts
      - ./transform:/app/transform
      - ./tests:/app/tests
      # Mounting data directory so DuckDB presists between runs
      - ./data:/app/data
    # Overriding the default CMD to keep the container alive for now
    # This lets me run commands interactively during development
    command: ["sleep", "infinity"]
    ports:
      - "8080:8080"

    # Allows the container to reach Tautulli on local machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prefect-server
    
volumes:
  prefect-data: